name: python-lint

on: [push, pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
    - uses: actions/checkout@v2  
    - name: Python Linter
      uses: sunnysid3up/python-linter@master
      with:
        source: "."
        mypy-options: "--ignore-missing-imports --show-error-codes"
        pylint-options: ""
        isort-options: "-w 100",
        django: false
